<?php
// $Id:$

/**
 * @file
 * Allow filtering messages by the realms they belong to.
 */

/**
 * Minimum CTools version needed.
 */
define('MESSAGE_REALM_REQUIRED_CTOOLS_API', '2.0-alpha1');

define('MESSAGE_FIELD_MESSAGE_REALM', 'message_realm_realm');

define('MESSAGE_FIELD_MESSAGE_REALM_ID', 'message_realm_realm_id');

/**
 * Implementation of hook_views_api().
 */
function message_realm_views_api() {
  return array(
    'api' => 2.0,
    'path' => drupal_get_path('module', 'message_realm') . '/includes',
  );
}

/**
 * Implementation of hook_ctools_plugin_api().
 */
function message_realm_ctools_plugin_api($module, $api) {
  if ($module == 'message_realm' && $api == 'plugins') {
    return array('version' => 1);
  }
}

/**
 * Implementation of hook_ctools_plugin_directory().
 */
function message_realm_ctools_plugin_directory($module, $type) {
  // Safety: go away if CTools is not at an appropriate version.
  if (!module_invoke('ctools', 'api_version', MESSAGE_REALM_REQUIRED_CTOOLS_API)) {
    return;
  }
  if ($module =='message_realm' && $type == 'message_realm') {
    return 'plugins/message_realm';
  }
}

/**
 * Implements hook_ctools_plugin_type()
 *
 * Inform the plugin system that Message realm module owns message.
 */
function message_realm_ctools_plugin_type() {
  $items = array();

  $items['message'] = array(
    'process' => array(
      'function' => 'message_realm_plugin_process',
      'file' => 'base.inc',
      'path' => drupal_get_path('module', 'message_realm') . '/plugins/message_realm',
    ),
    'classes' => array('handler'),
  );

  return $items;
}

/**
 * Return array of realms keyed by the plugin name and the realm title as value.
 */
function message_realm_get_realm_types() {
  $options = &drupal_static(__FUNCTION__, array());
  if (empty($options)) {
    foreach (message_realm_get_plugin_message_realms() as $plugin) {
      if (!empty($plugin['realm'])) {
        $options[$plugin['name']] = check_plain($plugin['title']);
      }
    }
  }

  return $options;
}

function message_realm_get_plugin_message_realm($plugin_name) {
  ctools_include('plugins');
  return ctools_get_plugins('message_realm', 'message_realm', $plugin_name);
}

function message_realm_get_plugin_message_realms() {
  ctools_include('plugins');
  return ctools_get_plugins('message_realm', 'message_realm');
}


